[build]
  publish = "build"
  command = "npm install && npm run build"

  #The following redirect is intended to redirect to api
  [[redirects]]
   from = "/api/*"
   to = "https://cartmax-server.herokuapp.com"
   status = 200

   [[redirects]]
     from = "/*"
     to = "/index.html"
     status = 200