[build]
  publish = "build"
  command = "CI=false npm run build"

  [[redirects]]
   /api/* "https://cartmax-server.herokuapp.com"
   /* "/index.html 200" 

  #The following redirect is intended to redirect to api
  [[redirects]]
   from = "/api/*"
   to = "https://cartmax-server.herokuapp.com"
   status = 200

   [[redirects]]
     from = "/*"
     to = "/index.html"
     status = 200

    