const data = {
  products: [
    {
      name: 'Allen Solly Slim fit shirt',
      slug: 'allen-solly-slim-fit-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 1199,
      countInStock: 13,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Arrow Slim fit shirt',
      slug: 'arrow-slim-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 1399,
      countInStock: 13,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Allen Solly Slim casual pant',
      slug: 'allen-solly-slim-casual-pant',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 1249,
      countInStock: 13,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Arrow Slim casual pant',
      slug: 'arrow-slim-casual-pant',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 1449,
      countInStock: 13,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
